### ISSUE TITLE
Release updated version for svelte 4

### ISSUE THREAD

**Issue by gtnbssn** [wh0am1-dev/svelte-zdog#1]
Hi there,

the package on npm is from version 0.3, installing gives issues with svelte 4:

```
 WARN  Issues with peer dependencies found
sites/wellbeing-youth-arts
└─┬ svelte-zdog 0.3.0
  └── ✕ unmet peer svelte@^3.54.0: found 4.0.4
```

It looks like the changes have been made in this repo but aren't available on npm yet.

**Comment by wh0am1-dev** [comment]
Noted, I'll take a look during this week !
Thanks for reporting 🖤
