### ISSUE TITLE
Are the props reactive?

### ISSUE THREAD

**Issue by gtnbssn** [wh0am1-dev/svelte-zdog#2]
I am trying to tween some translate values but am struggling. Maybe I am just doing it wrong?

I have a component that defines an object, it accepts objectX, objectY and objectZ as props.

These values are tweened stores defined higher up. I pass them to the component and things are properly placed at first, but when values change later the object does not move.

A much more simple example is to  have a button that toggles a boolean on click, and create a shape with something like `translate={{ x: boolean ? 100 : 200}}`. I did not manage to get the object to move.

**Comment by wh0am1-dev** [comment]
Props are not reactive, they are just passed as an initial config when instantiating a Zdog shape class underneath.

You can update a node using the `update` prop:

```svelte
<script lang="ts">
  import { Illustration, Ellipse } from 'svelte-zdog'
  let condition = false
</script>

{condition}

<button on:click={() => (condition = !condition)}>
  toggle
</button>

<Illustration element="svg" width={240} height={240}>
  <Ellipse
    translate={{ x: 10 }}
    update={node => delta => {
      node.translate.x = condition ? 20 : 10
    }}
  />
</Illustration>
```

**Comment by gtnbssn** [comment]
Thanks!! Does this mean the code in update is evaluated at every tick?

**Comment by wh0am1-dev** [comment]
Yes, It uses `requestAnimationFrame`:
https://github.com/wh0am1-dev/svelte-zdog/blob/948db029bfa78ef7e4a2dafbb1eea38eb3881604/src/lib/Illustration.svelte#L77
